import { createClient } from '@supabase/supabase-js';
import { projectId as makeProjectId } from '../../utils/supabase/info';

export const supabaseUrl = 'https://wsdxtflqoghexndbeetn.supabase.co';

export const supabaseAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzZHh0Zmxxb2doZXhuZGJlZXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNDQzOTksImV4cCI6MjA5MTkyMDM5OX0.6iS4yQWo6tv7k6UfYl9uzuHL2U_YbczGLw76y55LIDM';

// Cross-check: Figma Make's autogenerated info.tsx must match src/lib/supabase.ts.
// If they diverge, the platform deploy may silently route auth to the wrong project.
const expectedProjectId = 'wsdxtflqoghexndbeetn';
if (makeProjectId !== expectedProjectId) {
  console.error(
    `[UniRoom] ⚠️ SUPABASE PROJECT MISMATCH!\n` +
    `  utils/supabase/info.tsx → projectId = "${makeProjectId}"\n` +
    `  src/lib/supabase.ts     → URL projectId = "${expectedProjectId}"\n` +
    `  O deploy Figma Make pode estar a usar o projecto ERRADO.\n` +
    `  Fix: reconecta o projeto Supabase nas definições do Figma Make.`,
  );
} else {
  console.log('[UniRoom] ✓ Supabase projectId alinhado:', expectedProjectId);
}

export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey);

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});